#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
}

use Symfony\Component\Console\Application;
use Aschmelyun\Cleaver\Commands\BuildCommand;

$application = new Application('Cleaver', '1.5');

$application->add(new BuildCommand());

$application->run();